### PR TITLE
Add markdown templates for upstream preparation.

### PR DESCRIPTION
**Pull request by HanFa**
Use this thread to discuss upstream templating, including

1. PR templates
2. Issue templates
3. Labels/Milestones
4. CODEOWNER
5. Other documents to make potential outside contributors can easily ramp up
6. Bots / Automations

### CODE REVIEW

**Review by XudongLiuHarold — COMMENTED** [review]
Hi @HanFa  could you take a look at: https://github.com/vmware-tanzu/tanzu-framework/tree/main/.github/ISSUE_TEMPLATE and https://github.com/vmware-tanzu/tanzu-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md to see if we can align with this format?

**Comment by XudongLiuHarold** [comment]
BTW, maybe I am asking too much, could you do an investigation on can we have a bot to help us on labelling PRs and issues just like Kubernetes community doing now?
Something like, I can 
/ok-to-merge then it will label this.

Not a must-have one, just want to have a try. @HanFa 

Thank you!

**Comment by HanFa** [comment]
Good point! I see that most open-source projects nowadays have bots.

Let me do some research on how to build ones! 


> BTW, maybe I am asking too much, could you do an investigation on can we have a bot to help us on labelling PRs and issues just like Kubernetes community doing now?
> Something like, I can
> /ok-to-merge then it will label this.
> 
> Not a must-have one, just want to have a try. @HanFa
> 
> Thank you!

**Comment by HanFa** [comment]
> Hi @HanFa could you take a look at: https://github.com/vmware-tanzu/tanzu-framework/tree/main/.github/ISSUE_TEMPLATE and https://github.com/vmware-tanzu/tanzu-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md to see if we can align with this format?

Yes, they should be aligned or at least resemble others, since most of the template structures also apply to our project.

**Review by XudongLiuHarold — APPROVED** [review]
LGTM, good job!

**Pull request merged**
